FROM node:21 AS builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY api_clients ./api_clients
COPY app ./app
COPY assets ./assets
COPY next-env.d.ts ./
COPY tsconfig.json ./
COPY next.config.js ./
ARG baseUrl

RUN echo NEXT_PUBLIC_BASE_URL="$baseUrl" >> ./.env
RUN npm run build


FROM node:21 AS runner
WORKDIR /app
COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.next/standalone ./
ENV NODE_ENV production
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs
USER nextjs
EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD node -e "require('http').get('http://127.0.0.1:3000/', res => process.exit(res.statusCode < 500 ? 0 : 1)).on('error', () => process.exit(1))"
CMD ["node", "server.js"]