FROM node:21 AS builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY api_clients ./api_clients
COPY app ./app
COPY assets ./assets
COPY tsconfig.json ./
COPY vite.config.ts ./
COPY react-router.config.ts ./
ARG baseUrl
ARG gaId

RUN echo VITE_BASE_URL="$baseUrl" >> ./.env
RUN echo VITE_GA_ID="$gaId" >> ./.env
RUN npm run build


FROM node:21-slim AS runner
WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ENV NODE_ENV=production
EXPOSE 3000
ENV PORT=3000
CMD ["node_modules/.bin/react-router-serve", "./build/server/index.js"]
