FROM python:3.12
WORKDIR /app
COPY ./requirements.lock ./requirements.lock
COPY ./pyproject.toml ./pyproject.toml
RUN PYTHONDONTWRITEBYTECODE=1 pip install --no-cache-dir --upgrade -r requirements.lock
COPY ./icha ./icha
COPY ./migrations ./migrations
COPY ./app.py ./app.py
COPY ./alembic.ini ./alembic.ini
CMD ["bash", "-c","alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 80"]