FROM python:3.12
WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./icha ./icha
COPY ./migrations ./migrations
COPY ./app.py ./app.py
CMD [
    "bash", "-c","alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 80"
]