FROM node:21 AS builder
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY api_clients ./api_clients
COPY app ./app
COPY assets ./assets
COPY tsconfig.json ./
COPY vite.config.ts ./
COPY react-router.config.ts ./
ARG baseUrl
ARG gaId

RUN echo VITE_BASE_URL="$baseUrl" >> ./.env
RUN echo VITE_GA_ID="$gaId" >> ./.env
RUN npm run build


FROM nginx:alpine AS runner
COPY --from=builder /app/build/client /usr/share/nginx/html
COPY <<'EOF' /etc/nginx/conf.d/default.conf
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
EOF
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
