version: "3.7"
services:
  back:
    image: python:3.12
    volumes:
      - ./requirements.lock:/srv/requirements.lock
      - ./icha:/srv/icha
      - ./app.py:/srv/app.py
      - ./.env:/srv/.env
    working_dir: /srv
    command:
      - bash
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements-dev.lock
        python -m uvicorn app:app --host 0.0.0.0 --reload
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8000/health || exit 1" ] # exitコードは 0 or 1 に揃えておく。
      start_period: "10s"
      retries: 30
      timeout: "5s"
      interval: "5s"
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/src
    command:
      - bash
      - -c
      - |
        docker-entrypoint.sh generate -i http://back:8000/openapi.json -g typescript-fetch -o /src/api_clients --skip-validate-spec
        chmod 777 -R /src/
    depends_on:
      back:
        condition: service_healthy

