version: "3.7"

services:
  back:
    image: python:3.12
    volumes:
      - ./:/srv
    working_dir: /srv
    command:
      - bash
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        python -m uvicorn app:app --host 0.0.0.0 --reload
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8000/health || exit 1" ] # exitコードは 0 or 1 に揃えておく。
      start_period: "10s"
      retries: 10
      timeout: "5s"
      interval: "10s"
  openapi-generator:
    image: openapitools/openapi-generator-cli
    volumes:
      - ./:/src
    command: generate -i http://back:8000/openapi.json -g typescript-axios -o /src/api_clients --skip-validate-spec
    depends_on:
      back:
        condition: service_healthy
