"""empty message

Revision ID: 751a4f832ea4
Revises: 
Create Date: 2024-02-13 17:35:17.315730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751a4f832ea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gacha',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('content',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gacha_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gacha_id'], ['gacha.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('licence',
    sa.Column('gacha_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('business', sa.String(length=128), nullable=False),
    sa.Column('post', sa.String(length=128), nullable=False),
    sa.Column('credit', sa.String(length=128), nullable=False),
    sa.Column('distribution', sa.String(length=128), nullable=False),
    sa.Column('material', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['gacha_id'], ['gacha.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gacha_id')
    )
    op.create_table('thumbnail',
    sa.Column('gacha_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(length=16000000), nullable=False),
    sa.ForeignKeyConstraint(['gacha_id'], ['gacha.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gacha_id')
    )
    op.create_table('content_image',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(length=16000000), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_image')
    op.drop_table('thumbnail')
    op.drop_table('licence')
    op.drop_table('content')
    op.drop_table('gacha')
    op.drop_table('user')
    # ### end Alembic commands ###
