"""empty message

Revision ID: a53c4703214a
Revises: aaa09967a4c5
Create Date: 2024-03-01 16:44:52.668664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a53c4703214a'
down_revision: Union[str, None] = 'aaa09967a4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_image', 'base64',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=32000000),
               existing_nullable=False)
    op.alter_column('thumbnail', 'base64',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=32000000),
               existing_nullable=False)
    op.add_column('user', sa.Column('self_produce', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'self_produce')
    op.alter_column('thumbnail', 'base64',
               existing_type=sa.Text(length=32000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('content_image', 'base64',
               existing_type=sa.Text(length=32000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
