"""empty message

Revision ID: aaa09967a4c5
Revises: 6fd04a4a778a
Create Date: 2024-02-26 11:35:29.381104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaa09967a4c5'
down_revision: Union[str, None] = '6fd04a4a778a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_image', 'base64',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=32000000),
               existing_nullable=False)
    op.alter_column('licence', 'text',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(length=4096),
               existing_nullable=False)
    op.alter_column('thumbnail', 'base64',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=32000000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thumbnail', 'base64',
               existing_type=sa.Text(length=32000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('licence', 'text',
               existing_type=sa.Text(length=4096),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('content_image', 'base64',
               existing_type=sa.Text(length=32000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
