"""empty message

Revision ID: f991e753a946
Revises: 751a4f832ea4
Create Date: 2024-02-18 00:55:58.702865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f991e753a946'
down_revision: Union[str, None] = '751a4f832ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_image', sa.Column('base64', sa.Text(length=16000000), nullable=False))
    op.drop_column('content_image', 'data')
    op.add_column('thumbnail', sa.Column('base64', sa.Text(length=16000000), nullable=False))
    op.drop_column('thumbnail', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnail', sa.Column('data', mysql.LONGTEXT(), nullable=False))
    op.drop_column('thumbnail', 'base64')
    op.add_column('content_image', sa.Column('data', mysql.LONGTEXT(), nullable=False))
    op.drop_column('content_image', 'base64')
    # ### end Alembic commands ###
