name: backend cd

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@v4
      # docker
      - uses: docker/login-action@v2
        with:
          registry: harbor.kigawa.net
          username: ${{ secrets.HARBOR_USER  }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: BuildAndPushImageOnHarbor
        run: |
          docker compose -f generate-openapi.yml -p icha up --abort-on-container-exit
          docker build ./ -t harbor.kigawa.net/fns/icha-front:${{ github.ref_name }}-${{ github.run_number }} \
           -f Dockerfile_front --build-arg hoge=hello baseUrl=https://icha-api.kigawa.net
          docker push harbor.kigawa.net/fns/fns-backend:${{ github.ref_name }}-${{ github.run_number }}
      # argo
      - name: checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: kigawa01/k8s
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update YAML File
        run: |
          yq -i '.spec.template.spec.containers[0].image = "harbor.kigawa.net/private/icha-front:${{ github.ref_name }}-${{ github.run_number }}"' \
          ./icha/front.yml

      - name: push
        run: |
          git config user.name githubActions
          git config user.email bot@example.com
          git add .
          git commit --author=. -m "update rev"
          git push
