name: test

on: [push]

jobs:
  front:
    strategy:
      matrix:
        conf:
          - nodeVer: "21.x"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.conf.nodeVer }}
      - run: npm ci
      - run: npm run build
  back:
    strategy:
      matrix:
        conf:
          - pythonVer: "3.12"
            preTestCmd: docker compose -f generate-openapi.yml -p icha up --abort-on-container-exit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.conf.pythonVer }}
      - run: pip install -r requirements.txt
      - run: python -c "import sys; print(sys.version)"
      - name: pre test cmd
        run: ${{ matrix.conf.preTestCmd }}
        if: ${{ matrix.conf.preTestCmd }}
      - run: pytest